/* =========================================================================
   exercises.js — the exercise library you pick from when adding an exercise.
   Bundled as static data so it works fully offline.

   Grouped by BODY PART (LIBRARY_GROUPS). Each entry also carries style /
   equipment TAGS (LIBRARY_TAGS: Barbell, Cable, Smith, Plyo, Olympic, CrossFit,
   Hyrox…) used by the library's filter chips and search.

   `loads` names the joints/areas an exercise stresses. The app shows a ⚠
   caution ONLY when one of those areas is one the current profile protects —
   so a healthy profile sees no warnings.

   Entry: { name, group, tags[], tracks, sets, reps, notes, loads? }
     tracks: 'weight' | 'bodyweight' | 'time'
     loads:  subset of BODY_AREAS keys (omit for joint-friendly moves)

   Generated from a compact table — keep names stable: saved plans refer to
   exercises by name.
   ========================================================================= */

const LIBRARY_GROUPS = ["Chest", "Back", "Shoulders", "Biceps", "Triceps", "Forearms", "Quads", "Hamstrings", "Glutes", "Calves", "Core", "Full Body", "Cardio & Conditioning"];

// Style / equipment filters shown as chips in the library.
const LIBRARY_TAGS = ["Barbell", "Dumbbell", "Cable", "Smith", "Machine", "Kettlebell", "Bodyweight", "Band", "Plyo", "Olympic", "CrossFit", "Hyrox", "Cardio"];

// Areas a profile can choose to protect. key -> label.
const BODY_AREAS = [
  { key: 'knees', label: 'Knees' },
  { key: 'shoulders', label: 'Shoulders' },
  { key: 'lower back', label: 'Lower back' },
  { key: 'neck', label: 'Neck' },
  { key: 'elbows', label: 'Elbows' },
  { key: 'wrists', label: 'Wrists' },
  { key: 'hips', label: 'Hips' },
  { key: 'ankles', label: 'Ankles' },
];

const EXERCISE_LIBRARY = [
  /* ---------------- Chest ---------------- */
  { name: "Barbell Bench Press", group: "Chest", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "6–10", notes: "Flat bench; lower under control to mid-chest.", loads: ["shoulders"] },
  { name: "Incline Barbell Bench Press", group: "Chest", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "8–10", notes: "30–45° bench for upper chest.", loads: ["shoulders"] },
  { name: "Decline Barbell Bench Press", group: "Chest", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "8–10", notes: "Lower-chest emphasis.", loads: ["shoulders"] },
  { name: "Floor Press", group: "Chest", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "8", notes: "Shorter range — kinder to the shoulders." },
  { name: "Landmine Chest Press", group: "Chest", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10 each", notes: "Angled single-arm press, shoulder-friendly." },
  { name: "Dumbbell Bench Press", group: "Chest", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "8–12", notes: "Free arm path; go only as deep as feels good.", loads: ["shoulders"] },
  { name: "Incline Dumbbell Press", group: "Chest", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "8–12", notes: "Upper chest.", loads: ["shoulders"] },
  { name: "Decline Dumbbell Press", group: "Chest", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10", notes: "Lower chest.", loads: ["shoulders"] },
  { name: "Dumbbell Fly", group: "Chest", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12", notes: "Soft elbows, stretch without forcing depth.", loads: ["shoulders"] },
  { name: "Incline Dumbbell Fly", group: "Chest", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12", notes: "Upper-chest fly.", loads: ["shoulders"] },
  { name: "Dumbbell Squeeze Press", group: "Chest", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10–12", notes: "Press the dumbbells together the whole rep." },
  { name: "Dumbbell Pullover", group: "Chest", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12", notes: "Chest and lats; keep the ribs down.", loads: ["shoulders"] },
  { name: "Smith Machine Bench Press", group: "Chest", tags: ["Smith"], tracks: "weight", sets: 3, reps: "8–10", notes: "Fixed path — easy to push hard safely.", loads: ["shoulders"] },
  { name: "Smith Machine Incline Press", group: "Chest", tags: ["Smith"], tracks: "weight", sets: 3, reps: "8–10", notes: "Upper chest on the Smith.", loads: ["shoulders"] },
  { name: "Smith Machine Decline Press", group: "Chest", tags: ["Smith"], tracks: "weight", sets: 3, reps: "10", notes: "Lower chest on the Smith.", loads: ["shoulders"] },
  { name: "Chest Press Machine", group: "Chest", tags: ["Machine"], tracks: "weight", sets: 3, reps: "10–12", notes: "Seated, controlled — a bench-press alternative." },
  { name: "Incline Chest Press Machine", group: "Chest", tags: ["Machine"], tracks: "weight", sets: 3, reps: "10–12", notes: "Upper chest, supported." },
  { name: "Incline Machine Press (light)", group: "Chest", tags: ["Machine"], tracks: "weight", sets: 2, reps: "12", notes: "Only if pain-free; else swap for a cable fly." },
  { name: "Decline Chest Press Machine", group: "Chest", tags: ["Machine"], tracks: "weight", sets: 3, reps: "10–12", notes: "Lower chest, supported." },
  { name: "Plate-Loaded Chest Press", group: "Chest", tags: ["Machine"], tracks: "weight", sets: 3, reps: "8–12", notes: "Hammer-Strength style; can work one arm at a time." },
  { name: "Pec Deck", group: "Chest", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12–15", notes: "Chest isolation; stop short of a deep stretch." },
  { name: "Cable Chest Fly", group: "Chest", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12–15", notes: "Light, controlled range." },
  { name: "Cable Crossover", group: "Chest", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12–15", notes: "High-to-low; squeeze at the bottom." },
  { name: "Low-to-High Cable Fly", group: "Chest", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12–15", notes: "Upper-chest cable fly." },
  { name: "Single-Arm Cable Chest Press", group: "Chest", tags: ["Cable"], tracks: "weight", sets: 3, reps: "10 each", notes: "Core stays square as you press." },
  { name: "Standing Cable Chest Press", group: "Chest", tags: ["Cable"], tracks: "weight", sets: 3, reps: "10–12", notes: "Staggered stance, press forward." },
  { name: "Push-Up", group: "Chest", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10–20", notes: "Straight line head to heel.", loads: ["shoulders", "wrists"] },
  { name: "Incline Push-Up (hands elevated)", group: "Chest", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10–15", notes: "Easier push-up; wrist and shoulder friendlier." },
  { name: "Decline Push-Up", group: "Chest", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10–15", notes: "Feet up — harder, more upper chest.", loads: ["shoulders", "wrists"] },
  { name: "Wide Push-Up", group: "Chest", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10–15", notes: "More chest, less triceps.", loads: ["shoulders", "wrists"] },
  { name: "Ring Push-Up", group: "Chest", tags: ["Bodyweight", "CrossFit"], tracks: "bodyweight", sets: 3, reps: "8–12", notes: "Unstable rings — big stabiliser demand.", loads: ["shoulders", "wrists"] },
  { name: "Chest Dips", group: "Chest", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "8–12", notes: "Lean forward to bias the chest.", loads: ["shoulders"] },
  { name: "Plyo Push-Up", group: "Chest", tags: ["Plyo", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "6–8", notes: "Explode so the hands leave the floor.", loads: ["shoulders", "wrists", "elbows"] },
  { name: "Clap Push-Up", group: "Chest", tags: ["Plyo", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "5–8", notes: "Explosive push-up with a clap.", loads: ["shoulders", "wrists", "elbows"] },
  { name: "Medicine Ball Chest Pass", group: "Chest", tags: ["Plyo"], tracks: "bodyweight", sets: 3, reps: "8–10", notes: "Throw hard against a wall, catch, repeat." },
  { name: "Band Chest Press", group: "Chest", tags: ["Band"], tracks: "weight", sets: 3, reps: "15", notes: "Anchor behind you and press." },
  { name: "Band Chest Fly", group: "Chest", tags: ["Band"], tracks: "weight", sets: 3, reps: "15", notes: "Light, high-rep chest finisher." },

  /* ---------------- Back ---------------- */
  { name: "Conventional Deadlift", group: "Back", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "5", notes: "Hip hinge; bar close, back neutral.", loads: ["lower back"] },
  { name: "Sumo Deadlift", group: "Back", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "5", notes: "Wide stance, more upright torso.", loads: ["lower back", "hips"] },
  { name: "Trap Bar Deadlift", group: "Back", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "5–8", notes: "More upright — easier on the back and knees.", loads: ["lower back"] },
  { name: "Deficit Deadlift", group: "Back", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "5", notes: "Stand on a plate for extra range.", loads: ["lower back"] },
  { name: "Rack Pull", group: "Back", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "5–6", notes: "Partial deadlift from knee height.", loads: ["lower back"] },
  { name: "Barbell Row", group: "Back", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "8–10", notes: "Bent over, flat back, pull to the belly.", loads: ["lower back"] },
  { name: "Pendlay Row", group: "Back", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "6–8", notes: "Bar returns to the floor each rep.", loads: ["lower back"] },
  { name: "Yates Row", group: "Back", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "8–10", notes: "More upright, underhand row.", loads: ["lower back"] },
  { name: "T-Bar Row", group: "Back", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10", notes: "Mid-back thickness.", loads: ["lower back"] },
  { name: "Meadows Row", group: "Back", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10 each", notes: "Landmine single-arm row.", loads: ["lower back"] },
  { name: "Seal Row", group: "Back", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10", notes: "Lying on a bench — no lower-back load." },
  { name: "Single-Arm Dumbbell Row", group: "Back", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10 each", notes: "Supported on a bench." },
  { name: "Chest-Supported Row", group: "Back", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10–12", notes: "Face-down on an incline bench — back-friendly." },
  { name: "Kroc Row", group: "Back", tags: ["Dumbbell"], tracks: "weight", sets: 2, reps: "15–20", notes: "Heavy, high-rep single-arm row.", loads: ["lower back"] },
  { name: "Renegade Row", group: "Back", tags: ["Dumbbell", "CrossFit"], tracks: "weight", sets: 3, reps: "8 each", notes: "Row from a plank; hips stay square.", loads: ["wrists", "lower back"] },
  { name: "Seated Cable Row", group: "Back", tags: ["Cable"], tracks: "weight", sets: 3, reps: "10–12", notes: "Sit tall, pull to the stomach." },
  { name: "Wide-Grip Seated Cable Row", group: "Back", tags: ["Cable"], tracks: "weight", sets: 3, reps: "10–12", notes: "Upper back and rear delts." },
  { name: "Single-Arm Cable Row", group: "Back", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12 each", notes: "Full reach, full squeeze." },
  { name: "Lat Pulldown (wide grip)", group: "Back", tags: ["Cable"], tracks: "weight", sets: 3, reps: "10–12", notes: "Pull to the upper chest." },
  { name: "Lat Pulldown (neutral grip)", group: "Back", tags: ["Cable"], tracks: "weight", sets: 3, reps: "10–12", notes: "Shoulder-friendly grip." },
  { name: "Lat Pulldown (close grip)", group: "Back", tags: ["Cable"], tracks: "weight", sets: 3, reps: "10–12", notes: "V-handle, elbows to ribs." },
  { name: "Reverse-Grip Lat Pulldown", group: "Back", tags: ["Cable"], tracks: "weight", sets: 3, reps: "10–12", notes: "Underhand — more lower lats and biceps." },
  { name: "Single-Arm Lat Pulldown", group: "Back", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12 each", notes: "Unilateral lat work." },
  { name: "Straight-Arm Pulldown", group: "Back", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12–15", notes: "Lats without the biceps." },
  { name: "Cable Pullover (rope)", group: "Back", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12–15", notes: "Hinge slightly, sweep the rope to the thighs." },
  { name: "Face Pull", group: "Back", tags: ["Cable"], tracks: "weight", sets: 3, reps: "15", notes: "Rear delts and upper back — great for posture." },
  { name: "Machine Row", group: "Back", tags: ["Machine"], tracks: "weight", sets: 3, reps: "10–12", notes: "Chest pad keeps the spine unloaded." },
  { name: "Plate-Loaded Row", group: "Back", tags: ["Machine"], tracks: "weight", sets: 3, reps: "10 each", notes: "Hammer-Strength style unilateral row." },
  { name: "Assisted Pull-Up Machine", group: "Back", tags: ["Machine"], tracks: "bodyweight", sets: 3, reps: "8–12", notes: "Counterweight makes pull-ups trainable." },
  { name: "Reverse Pec Deck", group: "Back", tags: ["Machine"], tracks: "weight", sets: 3, reps: "15", notes: "Rear delts and upper back." },
  { name: "Back Extension (45°)", group: "Back", tags: ["Machine", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "12–15", notes: "Hinge at the hips; don't over-arch.", loads: ["lower back"] },
  { name: "Reverse Hyperextension", group: "Back", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12–15", notes: "Glutes and lower back, traction-friendly.", loads: ["lower back"] },
  { name: "Smith Machine Row", group: "Back", tags: ["Smith"], tracks: "weight", sets: 3, reps: "10", notes: "Bent-over row on a fixed path.", loads: ["lower back"] },
  { name: "Smith Machine Deadlift", group: "Back", tags: ["Smith"], tracks: "weight", sets: 3, reps: "8", notes: "Guided hinge.", loads: ["lower back"] },
  { name: "Smith Machine Rack Pull", group: "Back", tags: ["Smith"], tracks: "weight", sets: 3, reps: "6", notes: "Partial pull from the safeties.", loads: ["lower back"] },
  { name: "Pull-Up", group: "Back", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "5–10", notes: "Overhand, full hang to chin over bar.", loads: ["shoulders"] },
  { name: "Chin-Up", group: "Back", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "5–10", notes: "Underhand — more biceps.", loads: ["shoulders", "elbows"] },
  { name: "Neutral-Grip Pull-Up", group: "Back", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "5–10", notes: "Palms facing — easiest on the shoulders." },
  { name: "Kipping Pull-Up", group: "Back", tags: ["CrossFit", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10–15", notes: "Hip drive for volume; build strict strength first.", loads: ["shoulders"] },
  { name: "Butterfly Pull-Up", group: "Back", tags: ["CrossFit", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10–20", notes: "Fast cyclical kip — advanced.", loads: ["shoulders"] },
  { name: "Chest-to-Bar Pull-Up", group: "Back", tags: ["CrossFit", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "8–12", notes: "Chest touches the bar.", loads: ["shoulders"] },
  { name: "Bar Muscle-Up", group: "Back", tags: ["CrossFit", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "3–6", notes: "Pull and press over the bar.", loads: ["shoulders", "elbows", "wrists"] },
  { name: "Ring Muscle-Up", group: "Back", tags: ["CrossFit", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "3–5", notes: "False grip, pull, transition, dip.", loads: ["shoulders", "elbows", "wrists"] },
  { name: "Inverted Row", group: "Back", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10–15", notes: "Under a bar or Smith; body straight." },
  { name: "Ring Row", group: "Back", tags: ["Bodyweight", "CrossFit"], tracks: "bodyweight", sets: 3, reps: "10–15", notes: "Walk feet forward to make it harder." },
  { name: "Rope Climb", group: "Back", tags: ["CrossFit"], tracks: "bodyweight", sets: 3, reps: "2–3 climbs", notes: "Use a foot lock to save the arms.", loads: ["shoulders", "elbows"] },
  { name: "Superman", group: "Back", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "12", notes: "Lift arms and legs, squeeze the back.", loads: ["lower back"] },
  { name: "Band Lat Pulldown", group: "Back", tags: ["Band"], tracks: "weight", sets: 3, reps: "15", notes: "Anchor high and pull down." },
  { name: "Band Row", group: "Back", tags: ["Band"], tracks: "weight", sets: 3, reps: "15", notes: "Seated or standing band row." },
  { name: "Kettlebell Row", group: "Back", tags: ["Kettlebell"], tracks: "weight", sets: 3, reps: "10 each", notes: "Supported single-arm row." },
  { name: "Kettlebell Gorilla Row", group: "Back", tags: ["Kettlebell"], tracks: "weight", sets: 3, reps: "8 each", notes: "Alternate rows from a deep hinge.", loads: ["lower back"] },
  { name: "Kettlebell Deadlift", group: "Back", tags: ["Kettlebell"], tracks: "weight", sets: 3, reps: "10", notes: "Learn the hinge with a bell between the feet.", loads: ["lower back"] },

  /* ---------------- Shoulders ---------------- */
  { name: "Overhead Press (barbell)", group: "Shoulders", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "5–8", notes: "Strict standing press; squeeze glutes.", loads: ["shoulders", "lower back"] },
  { name: "Push Press", group: "Shoulders", tags: ["Barbell", "Olympic", "CrossFit"], tracks: "weight", sets: 3, reps: "5", notes: "Dip-and-drive into the press.", loads: ["shoulders"] },
  { name: "Behind-the-Neck Press", group: "Shoulders", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "8", notes: "Needs good shoulder mobility.", loads: ["shoulders", "neck"] },
  { name: "Z Press", group: "Shoulders", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "8", notes: "Seated on the floor — pure strict press.", loads: ["shoulders"] },
  { name: "Landmine Shoulder Press", group: "Shoulders", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10 each", notes: "Angled press — shoulder-friendly." },
  { name: "Upright Row", group: "Shoulders", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10–12", notes: "Stop around chest height.", loads: ["shoulders", "neck"] },
  { name: "Barbell Shrug", group: "Shoulders", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10–12", notes: "Traps; straight up and down.", loads: ["neck"] },
  { name: "Dumbbell Shoulder Press", group: "Shoulders", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "8–12", notes: "Seated or standing.", loads: ["shoulders"] },
  { name: "Arnold Press", group: "Shoulders", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10", notes: "Rotating press — hits all three heads.", loads: ["shoulders"] },
  { name: "Dumbbell Lateral Raise", group: "Shoulders", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12–15", notes: "Lead with the elbows, stop at shoulder height." },
  { name: "Front Raise", group: "Shoulders", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12", notes: "Front delts; controlled.", loads: ["shoulders"] },
  { name: "Rear Delt Fly", group: "Shoulders", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "15", notes: "Hinged over; light weight." },
  { name: "Dumbbell Y-Raise", group: "Shoulders", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12", notes: "Raise in a Y — lower traps and shoulder health." },
  { name: "Shrugs", group: "Shoulders", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12–15", notes: "Traps; hold the top.", loads: ["neck"] },
  { name: "Smith Machine Shoulder Press", group: "Shoulders", tags: ["Smith"], tracks: "weight", sets: 3, reps: "8–10", notes: "Seated guided press.", loads: ["shoulders"] },
  { name: "Smith Machine Shrug", group: "Shoulders", tags: ["Smith"], tracks: "weight", sets: 3, reps: "12", notes: "Heavy traps on a fixed path.", loads: ["neck"] },
  { name: "Machine Shoulder Press", group: "Shoulders", tags: ["Machine"], tracks: "weight", sets: 3, reps: "10–12", notes: "Supported pressing.", loads: ["shoulders"] },
  { name: "Machine Lateral Raise", group: "Shoulders", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12–15", notes: "Constant tension on the side delts." },
  { name: "Cable Lateral Raise", group: "Shoulders", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12–15", notes: "Smooth tension through the whole range." },
  { name: "Cable Front Raise", group: "Shoulders", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12", notes: "Front delts." },
  { name: "Cable Rear Delt Fly", group: "Shoulders", tags: ["Cable"], tracks: "weight", sets: 3, reps: "15", notes: "Cross the cables, pull wide." },
  { name: "Cable Y-Raise", group: "Shoulders", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12–15", notes: "Lower-trap and shoulder-health raise." },
  { name: "Cable Upright Row", group: "Shoulders", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12", notes: "Rope or bar, elbows lead.", loads: ["shoulders"] },
  { name: "Cable External Rotation", group: "Shoulders", tags: ["Cable"], tracks: "weight", sets: 3, reps: "15", notes: "Rotator cuff — keep it light." },
  { name: "Cable Internal Rotation", group: "Shoulders", tags: ["Cable"], tracks: "weight", sets: 3, reps: "15", notes: "Rotator cuff balance work." },
  { name: "Band Pull-Apart", group: "Shoulders", tags: ["Band"], tracks: "bodyweight", sets: 3, reps: "15–20", notes: "Rear delts and posture." },
  { name: "Band External Rotation", group: "Shoulders", tags: ["Band"], tracks: "weight", sets: 3, reps: "15", notes: "Rotator cuff warm-up." },
  { name: "Band Overhead Press", group: "Shoulders", tags: ["Band"], tracks: "weight", sets: 3, reps: "15", notes: "Light overhead pressing.", loads: ["shoulders"] },
  { name: "Pike Push-Up", group: "Shoulders", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "8–12", notes: "Hips high — bodyweight overhead press.", loads: ["shoulders", "wrists"] },
  { name: "Handstand Push-Up", group: "Shoulders", tags: ["Bodyweight", "CrossFit"], tracks: "bodyweight", sets: 3, reps: "5–10", notes: "Strict, against a wall.", loads: ["shoulders", "neck", "wrists"] },
  { name: "Kipping Handstand Push-Up", group: "Shoulders", tags: ["CrossFit"], tracks: "bodyweight", sets: 3, reps: "8–12", notes: "Hip drive for volume.", loads: ["shoulders", "neck", "wrists"] },
  { name: "Wall Walk", group: "Shoulders", tags: ["CrossFit", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "3–5", notes: "Walk up the wall to a handstand and back.", loads: ["shoulders", "wrists"] },
  { name: "Handstand Hold", group: "Shoulders", tags: ["Bodyweight", "CrossFit"], tracks: "time", sets: 3, reps: "20–45 sec", notes: "Wall-supported hold.", loads: ["shoulders", "wrists"] },
  { name: "Kettlebell Press", group: "Shoulders", tags: ["Kettlebell"], tracks: "weight", sets: 3, reps: "8 each", notes: "Single-arm strict press.", loads: ["shoulders"] },
  { name: "Bottoms-Up Kettlebell Press", group: "Shoulders", tags: ["Kettlebell"], tracks: "weight", sets: 3, reps: "6 each", notes: "Bell upside-down — great for stability.", loads: ["shoulders"] },
  { name: "Kettlebell Halo", group: "Shoulders", tags: ["Kettlebell"], tracks: "weight", sets: 3, reps: "8 each way", notes: "Circle the bell around the head — shoulder mobility." },

  /* ---------------- Biceps ---------------- */
  { name: "Barbell Curl", group: "Biceps", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "8–12", notes: "No swinging.", loads: ["elbows"] },
  { name: "EZ-Bar Curl", group: "Biceps", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10–12", notes: "Angled grip — easier on the wrists." },
  { name: "Drag Curl", group: "Biceps", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10", notes: "Drag the bar up the body, elbows back." },
  { name: "Preacher Curl", group: "Biceps", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10–12", notes: "Arm supported; don't hyperextend at the bottom.", loads: ["elbows"] },
  { name: "Dumbbell Biceps Curl", group: "Biceps", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10–12", notes: "Palms up, elbows still." },
  { name: "Biceps Curl", group: "Biceps", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12", notes: "Controlled curl." },
  { name: "Hammer Curl", group: "Biceps", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10–12", notes: "Neutral grip — biceps and forearms." },
  { name: "Incline Dumbbell Curl", group: "Biceps", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10–12", notes: "Long-head stretch on an incline bench.", loads: ["shoulders"] },
  { name: "Concentration Curl", group: "Biceps", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12 each", notes: "Seated, elbow braced on the thigh." },
  { name: "Zottman Curl", group: "Biceps", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10", notes: "Curl up palms-up, lower palms-down." },
  { name: "Spider Curl", group: "Biceps", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12", notes: "Chest on an incline bench, arms hanging." },
  { name: "Cross-Body Hammer Curl", group: "Biceps", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10 each", notes: "Curl across the body." },
  { name: "Cable Biceps Curl", group: "Biceps", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12", notes: "Constant tension." },
  { name: "Cable Hammer Curl (rope)", group: "Biceps", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12", notes: "Rope, neutral grip." },
  { name: "Bayesian Cable Curl", group: "Biceps", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12 each", notes: "Facing away from the stack — long-head stretch." },
  { name: "High Cable Curl", group: "Biceps", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12–15", notes: "Arms out at shoulder height, curl in." },
  { name: "Single-Arm Cable Curl", group: "Biceps", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12 each", notes: "Unilateral cable curl." },
  { name: "Machine Preacher Curl", group: "Biceps", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12", notes: "Supported curl.", loads: ["elbows"] },
  { name: "Machine Biceps Curl", group: "Biceps", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12", notes: "Fixed-path curl." },
  { name: "Band Curl", group: "Biceps", tags: ["Band"], tracks: "weight", sets: 3, reps: "15–20", notes: "High-rep pump." },
  { name: "Kettlebell Curl", group: "Biceps", tags: ["Kettlebell"], tracks: "weight", sets: 3, reps: "12", notes: "Hold the horns or handle." },

  /* ---------------- Triceps ---------------- */
  { name: "Close-Grip Bench Press", group: "Triceps", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "8", notes: "Hands shoulder-width; triceps drive.", loads: ["shoulders", "elbows"] },
  { name: "Skull Crushers", group: "Triceps", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10–12", notes: "Lower to the forehead, elbows in.", loads: ["elbows"] },
  { name: "JM Press", group: "Triceps", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "8", notes: "Hybrid of close-grip press and skull crusher.", loads: ["elbows"] },
  { name: "Smith Machine Close-Grip Press", group: "Triceps", tags: ["Smith"], tracks: "weight", sets: 3, reps: "10", notes: "Guided triceps press.", loads: ["elbows"] },
  { name: "Overhead Triceps Extension", group: "Triceps", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12", notes: "Long-head stretch overhead.", loads: ["shoulders", "elbows"] },
  { name: "Dumbbell Skull Crusher", group: "Triceps", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12", notes: "Neutral grip, easier on the elbows.", loads: ["elbows"] },
  { name: "Dumbbell Kickback", group: "Triceps", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12–15", notes: "Upper arm still, extend fully." },
  { name: "Tate Press", group: "Triceps", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12", notes: "Dumbbells to the chest, elbows out.", loads: ["elbows"] },
  { name: "Triceps Rope Pushdown", group: "Triceps", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12", notes: "Keep elbows tucked; spread the rope at the bottom." },
  { name: "Straight-Bar Pushdown", group: "Triceps", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12", notes: "Heavier pushdown variation." },
  { name: "V-Bar Pushdown", group: "Triceps", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12", notes: "Neutral-ish grip." },
  { name: "Reverse-Grip Pushdown", group: "Triceps", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12–15", notes: "Underhand — medial head." },
  { name: "Single-Arm Cable Pushdown", group: "Triceps", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12 each", notes: "Unilateral pushdown." },
  { name: "Overhead Cable Extension (rope)", group: "Triceps", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12", notes: "Facing away, extend overhead.", loads: ["shoulders", "elbows"] },
  { name: "Triceps Cable Kickback", group: "Triceps", tags: ["Cable"], tracks: "weight", sets: 3, reps: "15", notes: "Constant tension kickback." },
  { name: "Cable Cross-Body Extension", group: "Triceps", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12 each", notes: "Extend across the body." },
  { name: "Machine Triceps Extension", group: "Triceps", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12", notes: "Supported extension." },
  { name: "Assisted Dip Machine", group: "Triceps", tags: ["Machine"], tracks: "bodyweight", sets: 3, reps: "10–12", notes: "Counterweighted dips.", loads: ["shoulders"] },
  { name: "Dips", group: "Triceps", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "8–12", notes: "Upright torso for triceps.", loads: ["shoulders"] },
  { name: "Bench Dips", group: "Triceps", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "12–15", notes: "Hands on a bench behind you.", loads: ["shoulders", "wrists"] },
  { name: "Diamond Push-Up", group: "Triceps", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "8–12", notes: "Hands together under the chest.", loads: ["wrists", "elbows"] },
  { name: "Ring Dips", group: "Triceps", tags: ["Bodyweight", "CrossFit"], tracks: "bodyweight", sets: 3, reps: "6–10", notes: "Unstable — keep the rings close.", loads: ["shoulders"] },
  { name: "Band Pushdown", group: "Triceps", tags: ["Band"], tracks: "weight", sets: 3, reps: "20", notes: "High-rep finisher." },
  { name: "Kettlebell Overhead Extension", group: "Triceps", tags: ["Kettlebell"], tracks: "weight", sets: 3, reps: "12", notes: "Hold by the horns overhead.", loads: ["shoulders", "elbows"] },

  /* ---------------- Forearms ---------------- */
  { name: "Wrist Curl", group: "Forearms", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "15", notes: "Forearms on thighs, curl the wrists.", loads: ["wrists"] },
  { name: "Reverse Wrist Curl", group: "Forearms", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "15", notes: "Palms down, extensors.", loads: ["wrists"] },
  { name: "Reverse Curl", group: "Forearms", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "12", notes: "Overhand curl — forearms and brachialis.", loads: ["wrists", "elbows"] },
  { name: "Cable Wrist Curl", group: "Forearms", tags: ["Cable"], tracks: "weight", sets: 3, reps: "15", notes: "Smooth tension on the flexors.", loads: ["wrists"] },
  { name: "Farmer's Carry", group: "Forearms", tags: ["Dumbbell", "Kettlebell", "Hyrox"], tracks: "weight", sets: 3, reps: "40 m", notes: "Heavy walk — grip, traps and core. A Hyrox station." },
  { name: "Suitcase Carry", group: "Forearms", tags: ["Kettlebell", "Dumbbell"], tracks: "weight", sets: 3, reps: "30 m each", notes: "One-sided carry — anti-lean core work." },
  { name: "Plate Pinch Hold", group: "Forearms", tags: ["Other"], tracks: "time", sets: 3, reps: "20–30 sec", notes: "Pinch two plates smooth-side out." },
  { name: "Dead Hang", group: "Forearms", tags: ["Bodyweight"], tracks: "time", sets: 3, reps: "30–60 sec", notes: "Grip endurance and shoulder decompression.", loads: ["shoulders"] },
  { name: "Towel Hang", group: "Forearms", tags: ["Bodyweight"], tracks: "time", sets: 3, reps: "20–40 sec", notes: "Hang from towels over the bar — brutal grip.", loads: ["shoulders"] },
  { name: "Wrist Roller", group: "Forearms", tags: ["Other"], tracks: "weight", sets: 3, reps: "2–3 rolls", notes: "Roll the weight up and down.", loads: ["wrists"] },
  { name: "Gripper Squeeze", group: "Forearms", tags: ["Other"], tracks: "bodyweight", sets: 3, reps: "15 each", notes: "Hand gripper for crushing strength." },

  /* ---------------- Quads ---------------- */
  { name: "Barbell Back Squat", group: "Quads", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "5–8", notes: "Brace hard, sit between the hips.", loads: ["knees", "lower back"] },
  { name: "Front Squat", group: "Quads", tags: ["Barbell", "Olympic"], tracks: "weight", sets: 3, reps: "5–8", notes: "Upright torso, elbows high.", loads: ["knees", "wrists"] },
  { name: "Pause Squat", group: "Quads", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "5", notes: "Two-second pause in the hole.", loads: ["knees", "lower back"] },
  { name: "Box Squat", group: "Quads", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "8–10", notes: "Sitting to a box controls depth — kinder to the knee." },
  { name: "Zercher Squat", group: "Quads", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "8", notes: "Bar in the crook of the elbows.", loads: ["knees", "lower back"] },
  { name: "Overhead Squat", group: "Quads", tags: ["Barbell", "Olympic", "CrossFit"], tracks: "weight", sets: 3, reps: "5", notes: "Bar locked overhead — mobility demanding.", loads: ["knees", "shoulders", "wrists"] },
  { name: "Barbell Lunge", group: "Quads", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10 each", notes: "Bar on the back, step forward.", loads: ["knees"] },
  { name: "Landmine Squat", group: "Quads", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10", notes: "Hold the bar end at the chest.", loads: ["knees"] },
  { name: "Goblet Squat", group: "Quads", tags: ["Dumbbell", "Kettlebell"], tracks: "weight", sets: 3, reps: "10–12", notes: "Weight at the chest keeps you upright.", loads: ["knees"] },
  { name: "Dumbbell Squat", group: "Quads", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10–12", notes: "Dumbbells at the sides.", loads: ["knees"] },
  { name: "Bulgarian Split Squat", group: "Quads", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "8–10 each", notes: "Rear foot elevated.", loads: ["knees", "hips"] },
  { name: "Walking Lunge", group: "Quads", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10 each", notes: "Long steps, torso tall.", loads: ["knees"] },
  { name: "Reverse Lunge", group: "Quads", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10 each", notes: "Step back — easier on the knees than forward lunges.", loads: ["knees"] },
  { name: "Split Squat", group: "Quads", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10 each", notes: "Static lunge, straight down and up.", loads: ["knees"] },
  { name: "Step-Ups (low box)", group: "Quads", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10 each leg", notes: "Shallow height, controlled." },
  { name: "Step-Up (high box)", group: "Quads", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "8 each", notes: "Drive through the top foot.", loads: ["knees"] },
  { name: "Cossack Squat", group: "Quads", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "8 each", notes: "Side-to-side deep squat.", loads: ["knees", "hips"] },
  { name: "Leg Press", group: "Quads", tags: ["Machine"], tracks: "weight", sets: 3, reps: "10–12", notes: "Knee-friendly squat alternative; don't lock out hard." },
  { name: "Recumbent-style Leg Press (feet high)", group: "Quads", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12", notes: "High feet shift load to glutes and hamstrings." },
  { name: "Single-Leg Leg Press", group: "Quads", tags: ["Machine"], tracks: "weight", sets: 3, reps: "10 each", notes: "Fix left/right imbalances." },
  { name: "Hack Squat", group: "Quads", tags: ["Machine"], tracks: "weight", sets: 3, reps: "8–10", notes: "Quad-dominant machine squat.", loads: ["knees"] },
  { name: "Pendulum Squat", group: "Quads", tags: ["Machine"], tracks: "weight", sets: 3, reps: "10", notes: "Smooth arc, deep quad stretch.", loads: ["knees"] },
  { name: "Belt Squat", group: "Quads", tags: ["Machine"], tracks: "weight", sets: 3, reps: "10", notes: "Loads the legs without loading the spine." },
  { name: "Leg Extension", group: "Quads", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12–15", notes: "Quad isolation; control the top.", loads: ["knees"] },
  { name: "Single-Leg Extension", group: "Quads", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12 each", notes: "Unilateral quad work.", loads: ["knees"] },
  { name: "Sissy Squat", group: "Quads", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10", notes: "Knees forward, lean back — quad burner.", loads: ["knees"] },
  { name: "Smith Machine Squat", group: "Quads", tags: ["Smith"], tracks: "weight", sets: 3, reps: "8–10", notes: "Guided squat; feet slightly forward.", loads: ["knees"] },
  { name: "Smith Machine Front Squat", group: "Quads", tags: ["Smith"], tracks: "weight", sets: 3, reps: "8–10", notes: "Upright quad squat.", loads: ["knees"] },
  { name: "Smith Machine Split Squat", group: "Quads", tags: ["Smith"], tracks: "weight", sets: 3, reps: "10 each", notes: "Stable split squat.", loads: ["knees"] },
  { name: "Smith Machine Lunge", group: "Quads", tags: ["Smith"], tracks: "weight", sets: 3, reps: "10 each", notes: "Guided reverse lunge.", loads: ["knees"] },
  { name: "Cable Goblet Squat", group: "Quads", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12", notes: "Hold a low cable at the chest.", loads: ["knees"] },
  { name: "Kettlebell Front Squat", group: "Quads", tags: ["Kettlebell"], tracks: "weight", sets: 3, reps: "10", notes: "Bells in the rack position.", loads: ["knees"] },
  { name: "Air Squat", group: "Quads", tags: ["Bodyweight", "CrossFit"], tracks: "bodyweight", sets: 3, reps: "15–25", notes: "Full depth, heels down.", loads: ["knees"] },
  { name: "Wall Sit", group: "Quads", tags: ["Bodyweight"], tracks: "time", sets: 3, reps: "30–60 sec", notes: "Thighs parallel, back on the wall.", loads: ["knees"] },
  { name: "Pistol Squat", group: "Quads", tags: ["Bodyweight", "CrossFit"], tracks: "bodyweight", sets: 3, reps: "5 each", notes: "Single-leg squat to full depth.", loads: ["knees", "ankles"] },
  { name: "Jump Squat", group: "Quads", tags: ["Plyo"], tracks: "bodyweight", sets: 3, reps: "8–10", notes: "Explode up, land soft.", loads: ["knees", "ankles"] },
  { name: "Box Jump", group: "Quads", tags: ["Plyo", "CrossFit"], tracks: "bodyweight", sets: 4, reps: "5", notes: "Jump up, step down.", loads: ["knees", "ankles"] },
  { name: "Box Jump Over", group: "Quads", tags: ["Plyo", "CrossFit"], tracks: "bodyweight", sets: 3, reps: "10", notes: "Jump onto and over the box.", loads: ["knees", "ankles"] },
  { name: "Tuck Jump", group: "Quads", tags: ["Plyo"], tracks: "bodyweight", sets: 3, reps: "8", notes: "Knees to chest in the air.", loads: ["knees", "ankles"] },
  { name: "Split Squat Jump", group: "Quads", tags: ["Plyo"], tracks: "bodyweight", sets: 3, reps: "8 each", notes: "Switch legs mid-air.", loads: ["knees", "ankles"] },
  { name: "Jumping Lunge", group: "Quads", tags: ["Plyo"], tracks: "bodyweight", sets: 3, reps: "10 each", notes: "Alternating explosive lunges.", loads: ["knees", "ankles"] },
  { name: "Depth Jump", group: "Quads", tags: ["Plyo"], tracks: "bodyweight", sets: 3, reps: "5", notes: "Step off a box, rebound up instantly.", loads: ["knees", "ankles"] },
  { name: "Broad Jump", group: "Quads", tags: ["Plyo"], tracks: "bodyweight", sets: 4, reps: "5", notes: "Max distance forward, stick the landing.", loads: ["knees", "ankles"] },
  { name: "Sled Push", group: "Quads", tags: ["Hyrox", "CrossFit"], tracks: "weight", sets: 4, reps: "25 m", notes: "Low body angle, drive with the legs. A Hyrox station.", loads: ["knees"] },
  { name: "Sandbag Lunges", group: "Quads", tags: ["Hyrox"], tracks: "weight", sets: 3, reps: "25 m", notes: "Sandbag on the shoulders, knee kisses the floor. A Hyrox station.", loads: ["knees"] },

  /* ---------------- Hamstrings ---------------- */
  { name: "Romanian Deadlift", group: "Hamstrings", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "8–10", notes: "Hip hinge; neutral back, soft knees.", loads: ["lower back"] },
  { name: "Stiff-Leg Deadlift", group: "Hamstrings", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "8–10", notes: "Straighter legs than an RDL.", loads: ["lower back"] },
  { name: "Good Morning", group: "Hamstrings", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10", notes: "Bar on the back, hinge forward.", loads: ["lower back"] },
  { name: "Dumbbell Romanian Deadlift", group: "Hamstrings", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10", notes: "Dumbbells slide down the thighs.", loads: ["lower back"] },
  { name: "Single-Leg Romanian Deadlift", group: "Hamstrings", tags: ["Dumbbell", "Kettlebell"], tracks: "weight", sets: 3, reps: "8 each", notes: "Balance and hamstrings.", loads: ["lower back"] },
  { name: "Seated Leg Curl", group: "Hamstrings", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12", notes: "Hamstrings, knee-safe." },
  { name: "Lying Leg Curl", group: "Hamstrings", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12", notes: "Hamstring isolation." },
  { name: "Hamstring Curl Machine", group: "Hamstrings", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12", notes: "Controlled curl." },
  { name: "Standing Single-Leg Curl", group: "Hamstrings", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12 each", notes: "Unilateral hamstring curl." },
  { name: "Nordic Hamstring Curl", group: "Hamstrings", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "5", notes: "Lower yourself slowly — superb for hamstring resilience.", loads: ["knees"] },
  { name: "Glute-Ham Raise", group: "Hamstrings", tags: ["Machine", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "8", notes: "Hamstrings and glutes on a GHD." },
  { name: "Cable Leg Curl (standing)", group: "Hamstrings", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12 each", notes: "Ankle strap, curl the heel back." },
  { name: "Smith Machine Romanian Deadlift", group: "Hamstrings", tags: ["Smith"], tracks: "weight", sets: 3, reps: "10", notes: "Guided hinge.", loads: ["lower back"] },
  { name: "Smith Machine Good Morning", group: "Hamstrings", tags: ["Smith"], tracks: "weight", sets: 3, reps: "10", notes: "Guided good morning.", loads: ["lower back"] },
  { name: "Swiss Ball Leg Curl", group: "Hamstrings", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "12", notes: "Hips up, roll the ball in." },
  { name: "Sliding Leg Curl", group: "Hamstrings", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10", notes: "Heels on sliders or a towel." },
  { name: "Band Leg Curl", group: "Hamstrings", tags: ["Band"], tracks: "weight", sets: 3, reps: "15", notes: "Lying or standing band curl." },

  /* ---------------- Glutes ---------------- */
  { name: "Hip Thrust", group: "Glutes", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10–12", notes: "Big glute builder, easy on the knee." },
  { name: "Barbell Glute Bridge", group: "Glutes", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "12", notes: "Hip thrust from the floor." },
  { name: "Glute Bridge", group: "Glutes", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "12–15", notes: "Posterior chain, knee-safe." },
  { name: "Single-Leg Hip Thrust", group: "Glutes", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10 each", notes: "One leg at a time." },
  { name: "Smith Machine Hip Thrust", group: "Glutes", tags: ["Smith"], tracks: "weight", sets: 3, reps: "10–12", notes: "Stable, easy to load." },
  { name: "Hip Thrust Machine", group: "Glutes", tags: ["Machine"], tracks: "weight", sets: 3, reps: "10–12", notes: "Plate or pin loaded." },
  { name: "Hip Abduction (machine)", group: "Glutes", tags: ["Machine"], tracks: "weight", sets: 3, reps: "15", notes: "Glute medius; controlled." },
  { name: "Hip Adduction (machine)", group: "Glutes", tags: ["Machine"], tracks: "weight", sets: 3, reps: "15", notes: "Inner thighs; controlled." },
  { name: "Glute Kickback Machine", group: "Glutes", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12 each", notes: "Drive the heel back." },
  { name: "Cable Glute Kickback", group: "Glutes", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12 each", notes: "Ankle strap, squeeze at the top." },
  { name: "Cable Hip Abduction", group: "Glutes", tags: ["Cable"], tracks: "weight", sets: 3, reps: "15 each", notes: "Standing side leg raise." },
  { name: "Cable Pull-Through", group: "Glutes", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12–15", notes: "Hinge with a rope between the legs." },
  { name: "Dumbbell Sumo Squat", group: "Glutes", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "12", notes: "Wide stance, toes out.", loads: ["knees"] },
  { name: "Curtsy Lunge", group: "Glutes", tags: ["Dumbbell"], tracks: "weight", sets: 3, reps: "10 each", notes: "Step back and across.", loads: ["knees"] },
  { name: "Frog Pump", group: "Glutes", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "20", notes: "Soles together, short-range bridges." },
  { name: "Clamshell (band)", group: "Glutes", tags: ["Band"], tracks: "bodyweight", sets: 3, reps: "15 each", notes: "Side-lying, open the knees." },
  { name: "Banded Lateral Walk", group: "Glutes", tags: ["Band"], tracks: "bodyweight", sets: 3, reps: "12 each way", notes: "Band around the knees or ankles." },
  { name: "Monster Walk (band)", group: "Glutes", tags: ["Band"], tracks: "bodyweight", sets: 3, reps: "10 each", notes: "Diagonal steps against a band." },
  { name: "Donkey Kick", group: "Glutes", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "15 each", notes: "On all fours, kick up and back." },
  { name: "Fire Hydrant", group: "Glutes", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "12 each", notes: "On all fours, lift the knee out." },
  { name: "Lateral Bound", group: "Glutes", tags: ["Plyo"], tracks: "bodyweight", sets: 3, reps: "8 each", notes: "Leap side to side, stick each landing.", loads: ["knees", "ankles"] },
  { name: "Skater Jump", group: "Glutes", tags: ["Plyo"], tracks: "bodyweight", sets: 3, reps: "10 each", notes: "Speed-skater hops.", loads: ["knees", "ankles"] },

  /* ---------------- Calves ---------------- */
  { name: "Standing Calf Raise", group: "Calves", tags: ["Machine"], tracks: "weight", sets: 3, reps: "12–15", notes: "Full stretch, pause at the top.", loads: ["ankles"] },
  { name: "Seated Calf Raise", group: "Calves", tags: ["Machine"], tracks: "weight", sets: 3, reps: "15", notes: "Soleus focus." },
  { name: "Leg Press Calf Raise", group: "Calves", tags: ["Machine"], tracks: "weight", sets: 3, reps: "15", notes: "Toes on the sled edge." },
  { name: "Smith Machine Calf Raise", group: "Calves", tags: ["Smith"], tracks: "weight", sets: 3, reps: "15", notes: "Stand on a plate for range.", loads: ["ankles"] },
  { name: "Donkey Calf Raise", group: "Calves", tags: ["Machine"], tracks: "weight", sets: 3, reps: "15", notes: "Hinged-over calf raise.", loads: ["ankles"] },
  { name: "Single-Leg Calf Raise", group: "Calves", tags: ["Bodyweight", "Dumbbell"], tracks: "bodyweight", sets: 3, reps: "15 each", notes: "On a step for full range.", loads: ["ankles"] },
  { name: "Tibialis Raise", group: "Calves", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "20", notes: "Front-of-shin strength — good for knees and ankles." },
  { name: "Pogo Hops", group: "Calves", tags: ["Plyo"], tracks: "bodyweight", sets: 3, reps: "20", notes: "Quick stiff-ankle bounces.", loads: ["ankles"] },

  /* ---------------- Core ---------------- */
  { name: "Plank", group: "Core", tags: ["Bodyweight"], tracks: "time", sets: 3, reps: "30–60 sec", notes: "Brace like you're about to be punched.", loads: ["wrists"] },
  { name: "Side Plank", group: "Core", tags: ["Bodyweight"], tracks: "time", sets: 3, reps: "30 sec each", notes: "Obliques; stack the hips." },
  { name: "Copenhagen Plank", group: "Core", tags: ["Bodyweight"], tracks: "time", sets: 3, reps: "20 sec each", notes: "Adductors and obliques.", loads: ["knees"] },
  { name: "Dead Bug", group: "Core", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10 each", notes: "Lower back stays flat." },
  { name: "Bird Dog", group: "Core", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10 each", notes: "Reach long, hips level." },
  { name: "Pallof Press", group: "Core", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12 each", notes: "Anti-rotation — resist the pull." },
  { name: "Pallof Press (cable)", group: "Core", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12 each", notes: "Anti-rotation core." },
  { name: "Band Pallof Press", group: "Core", tags: ["Band"], tracks: "weight", sets: 3, reps: "12 each", notes: "Anti-rotation with a band." },
  { name: "Standing Cable Chop", group: "Core", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12 each", notes: "High-to-low, rotate through the hips." },
  { name: "Cable Lift (low-to-high)", group: "Core", tags: ["Cable"], tracks: "weight", sets: 3, reps: "12 each", notes: "Low-to-high rotation." },
  { name: "Cable Crunch", group: "Core", tags: ["Cable"], tracks: "weight", sets: 3, reps: "15", notes: "Kneeling, crunch the ribs to the hips.", loads: ["lower back"] },
  { name: "Cable Side Bend", group: "Core", tags: ["Cable"], tracks: "weight", sets: 3, reps: "15 each", notes: "Obliques; slow and controlled.", loads: ["lower back"] },
  { name: "Machine Crunch", group: "Core", tags: ["Machine"], tracks: "weight", sets: 3, reps: "15", notes: "Supported crunch." },
  { name: "Crunch", group: "Core", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "15–20", notes: "Short range, exhale at the top.", loads: ["neck"] },
  { name: "Bicycle Crunch", group: "Core", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "20 total", notes: "Elbow to opposite knee.", loads: ["neck"] },
  { name: "Decline Sit-Up", group: "Core", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "15", notes: "On a decline bench.", loads: ["lower back"] },
  { name: "AbMat Sit-Up", group: "Core", tags: ["CrossFit", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "20", notes: "Full-range sit-up with lumbar support." },
  { name: "GHD Sit-Up", group: "Core", tags: ["CrossFit", "Machine"], tracks: "bodyweight", sets: 3, reps: "10–15", notes: "Big range — start with low volume.", loads: ["lower back"] },
  { name: "V-Up", group: "Core", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "12", notes: "Touch hands to feet.", loads: ["lower back"] },
  { name: "Hollow Hold", group: "Core", tags: ["Bodyweight", "CrossFit"], tracks: "time", sets: 3, reps: "20–40 sec", notes: "Low back pressed down.", loads: ["lower back"] },
  { name: "Hollow Rock", group: "Core", tags: ["Bodyweight", "CrossFit"], tracks: "bodyweight", sets: 3, reps: "15", notes: "Rock in the hollow position.", loads: ["lower back"] },
  { name: "L-Sit", group: "Core", tags: ["Bodyweight", "CrossFit"], tracks: "time", sets: 3, reps: "10–20 sec", notes: "Legs straight out, on parallettes or a bench.", loads: ["wrists"] },
  { name: "Lying Leg Raise", group: "Core", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "12", notes: "Lower slowly; stop before the back arches.", loads: ["lower back"] },
  { name: "Hanging Knee Raise", group: "Core", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "12", notes: "Lower abs from a full hang.", loads: ["shoulders"] },
  { name: "Hanging Leg Raise", group: "Core", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10", notes: "Straight legs to 90° or higher.", loads: ["shoulders", "lower back"] },
  { name: "Toes-to-Bar", group: "Core", tags: ["CrossFit", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10–15", notes: "Kip and touch the bar with the toes.", loads: ["shoulders"] },
  { name: "Knees-to-Elbows", group: "Core", tags: ["CrossFit", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10", notes: "Knees touch the elbows from a hang.", loads: ["shoulders"] },
  { name: "Russian Twist", group: "Core", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "20 total", notes: "Loaded rotation.", loads: ["lower back"] },
  { name: "Ab Wheel Rollout", group: "Core", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "8–10", notes: "Advanced anti-extension; brace hard.", loads: ["lower back", "wrists"] },
  { name: "Mountain Climber", group: "Core", tags: ["Bodyweight", "CrossFit"], tracks: "time", sets: 3, reps: "30 sec", notes: "Fast knees, hips low.", loads: ["wrists"] },
  { name: "Flutter Kicks", group: "Core", tags: ["Bodyweight"], tracks: "time", sets: 3, reps: "30 sec", notes: "Small, fast leg kicks.", loads: ["lower back"] },
  { name: "Stir the Pot", group: "Core", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10 each way", notes: "Circle the elbows on a Swiss ball." },
  { name: "Dragon Flag", group: "Core", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "5", notes: "Very advanced full-body lever.", loads: ["lower back", "neck"] },
  { name: "Landmine Rotation", group: "Core", tags: ["Barbell"], tracks: "weight", sets: 3, reps: "10 each", notes: "Arc the bar side to side.", loads: ["lower back"] },
  { name: "Kettlebell Windmill", group: "Core", tags: ["Kettlebell"], tracks: "weight", sets: 3, reps: "6 each", notes: "Bell overhead, hinge sideways.", loads: ["shoulders", "lower back"] },

  /* ---------------- Full Body ---------------- */
  { name: "Power Clean", group: "Full Body", tags: ["Olympic", "Barbell", "CrossFit"], tracks: "weight", sets: 5, reps: "3", notes: "Floor to the front rack, catch high.", loads: ["lower back", "wrists"] },
  { name: "Hang Power Clean", group: "Full Body", tags: ["Olympic", "Barbell", "CrossFit"], tracks: "weight", sets: 5, reps: "3", notes: "Start from the hang above the knee.", loads: ["wrists"] },
  { name: "Squat Clean", group: "Full Body", tags: ["Olympic", "Barbell"], tracks: "weight", sets: 5, reps: "2", notes: "Catch in a full front squat.", loads: ["knees", "wrists"] },
  { name: "Clean Pull", group: "Full Body", tags: ["Olympic", "Barbell"], tracks: "weight", sets: 4, reps: "3", notes: "Explosive pull without the catch.", loads: ["lower back"] },
  { name: "Clean High Pull", group: "Full Body", tags: ["Olympic", "Barbell"], tracks: "weight", sets: 4, reps: "3", notes: "Pull to chest height, elbows high.", loads: ["shoulders"] },
  { name: "Clean & Jerk", group: "Full Body", tags: ["Olympic", "Barbell", "CrossFit"], tracks: "weight", sets: 5, reps: "1–2", notes: "The full lift — clean then jerk overhead.", loads: ["knees", "shoulders", "wrists"] },
  { name: "Split Jerk", group: "Full Body", tags: ["Olympic", "Barbell"], tracks: "weight", sets: 5, reps: "2", notes: "Drive and split under the bar.", loads: ["shoulders"] },
  { name: "Push Jerk", group: "Full Body", tags: ["Olympic", "Barbell", "CrossFit"], tracks: "weight", sets: 5, reps: "2", notes: "Drive and push under into a quarter squat.", loads: ["shoulders"] },
  { name: "Power Snatch", group: "Full Body", tags: ["Olympic", "Barbell", "CrossFit"], tracks: "weight", sets: 5, reps: "2", notes: "Floor to overhead in one move, catch high.", loads: ["shoulders", "wrists"] },
  { name: "Hang Snatch", group: "Full Body", tags: ["Olympic", "Barbell"], tracks: "weight", sets: 5, reps: "2", notes: "Snatch from the hang.", loads: ["shoulders", "wrists"] },
  { name: "Squat Snatch", group: "Full Body", tags: ["Olympic", "Barbell"], tracks: "weight", sets: 5, reps: "1–2", notes: "Catch in a full overhead squat.", loads: ["knees", "shoulders", "wrists"] },
  { name: "Snatch Pull", group: "Full Body", tags: ["Olympic", "Barbell"], tracks: "weight", sets: 4, reps: "3", notes: "Wide-grip explosive pull.", loads: ["lower back"] },
  { name: "Snatch Balance", group: "Full Body", tags: ["Olympic", "Barbell"], tracks: "weight", sets: 4, reps: "3", notes: "Drop under the bar into an overhead squat.", loads: ["knees", "shoulders", "wrists"] },
  { name: "Muscle Snatch", group: "Full Body", tags: ["Olympic", "Barbell"], tracks: "weight", sets: 4, reps: "3", notes: "No re-bend — builds turnover.", loads: ["shoulders"] },
  { name: "Thruster", group: "Full Body", tags: ["CrossFit", "Barbell"], tracks: "weight", sets: 3, reps: "10", notes: "Front squat straight into a press.", loads: ["knees", "shoulders"] },
  { name: "Dumbbell Thruster", group: "Full Body", tags: ["CrossFit", "Dumbbell"], tracks: "weight", sets: 3, reps: "12", notes: "Squat-to-press with dumbbells.", loads: ["knees", "shoulders"] },
  { name: "Dumbbell Snatch", group: "Full Body", tags: ["CrossFit", "Dumbbell", "Olympic"], tracks: "weight", sets: 3, reps: "10 each", notes: "Floor to overhead in one move.", loads: ["shoulders", "lower back"] },
  { name: "Dumbbell Clean & Jerk", group: "Full Body", tags: ["CrossFit", "Dumbbell"], tracks: "weight", sets: 3, reps: "8 each", notes: "Single-arm clean then press/jerk.", loads: ["shoulders"] },
  { name: "Devil Press", group: "Full Body", tags: ["CrossFit", "Dumbbell"], tracks: "weight", sets: 3, reps: "10", notes: "Burpee into a double-dumbbell snatch.", loads: ["shoulders", "wrists", "lower back"] },
  { name: "Man Maker", group: "Full Body", tags: ["CrossFit", "Dumbbell"], tracks: "weight", sets: 3, reps: "8", notes: "Push-up, rows, clean and press.", loads: ["shoulders", "wrists"] },
  { name: "Burpee", group: "Full Body", tags: ["CrossFit", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10–15", notes: "Chest to floor, jump and clap overhead.", loads: ["wrists", "knees"] },
  { name: "Bar-Facing Burpee", group: "Full Body", tags: ["CrossFit", "Bodyweight"], tracks: "bodyweight", sets: 3, reps: "10", notes: "Burpee then jump over a barbell.", loads: ["wrists", "knees"] },
  { name: "Burpee Box Jump-Over", group: "Full Body", tags: ["CrossFit", "Plyo"], tracks: "bodyweight", sets: 3, reps: "10", notes: "Burpee then jump over a box.", loads: ["knees", "ankles"] },
  { name: "Burpee Broad Jump", group: "Full Body", tags: ["Hyrox", "Plyo"], tracks: "bodyweight", sets: 3, reps: "10", notes: "Burpee then jump forward. A Hyrox station.", loads: ["knees", "ankles", "wrists"] },
  { name: "Wall Ball", group: "Full Body", tags: ["Hyrox", "CrossFit"], tracks: "weight", sets: 3, reps: "20", notes: "Squat and throw the ball to a target. A Hyrox station.", loads: ["knees", "shoulders"] },
  { name: "Kettlebell Swing", group: "Full Body", tags: ["Kettlebell", "CrossFit"], tracks: "weight", sets: 3, reps: "15–20", notes: "Hinge-driven swing to chest height.", loads: ["lower back"] },
  { name: "American Kettlebell Swing", group: "Full Body", tags: ["Kettlebell", "CrossFit"], tracks: "weight", sets: 3, reps: "15", notes: "Swing all the way overhead.", loads: ["shoulders", "lower back"] },
  { name: "Kettlebell Clean", group: "Full Body", tags: ["Kettlebell"], tracks: "weight", sets: 3, reps: "8 each", notes: "Swing into the rack position.", loads: ["wrists"] },
  { name: "Kettlebell Snatch", group: "Full Body", tags: ["Kettlebell"], tracks: "weight", sets: 3, reps: "8 each", notes: "Swing straight to overhead.", loads: ["shoulders", "wrists"] },
  { name: "Kettlebell Clean & Press", group: "Full Body", tags: ["Kettlebell"], tracks: "weight", sets: 3, reps: "6 each", notes: "Clean to the rack, then press.", loads: ["shoulders"] },
  { name: "Turkish Get-Up", group: "Full Body", tags: ["Kettlebell", "CrossFit"], tracks: "weight", sets: 3, reps: "3 each", notes: "Floor to standing with a bell overhead.", loads: ["shoulders"] },
  { name: "Sandbag Clean", group: "Full Body", tags: ["CrossFit"], tracks: "weight", sets: 3, reps: "8", notes: "Lift the bag from the floor to the chest.", loads: ["lower back"] },
  { name: "Sandbag to Shoulder", group: "Full Body", tags: ["CrossFit"], tracks: "weight", sets: 3, reps: "10", notes: "Floor to either shoulder.", loads: ["lower back"] },
  { name: "Sled Pull", group: "Full Body", tags: ["Hyrox"], tracks: "weight", sets: 4, reps: "25 m", notes: "Rope pull hand over hand. A Hyrox station.", loads: ["lower back"] },
  { name: "Tire Flip", group: "Full Body", tags: ["CrossFit"], tracks: "weight", sets: 3, reps: "6", notes: "Hips drive, push the tire over.", loads: ["lower back", "knees"] },
  { name: "Medicine Ball Slam", group: "Full Body", tags: ["CrossFit", "Plyo"], tracks: "weight", sets: 3, reps: "12–15", notes: "Lift overhead, slam into the floor.", loads: ["lower back"] },
  { name: "Medicine Ball Clean", group: "Full Body", tags: ["CrossFit"], tracks: "weight", sets: 3, reps: "10", notes: "Floor to chest with a med ball.", loads: ["lower back"] },
  { name: "Bear Crawl", group: "Full Body", tags: ["Bodyweight", "CrossFit"], tracks: "time", sets: 3, reps: "20 m", notes: "Knees just off the floor.", loads: ["wrists"] },
  { name: "Inchworm", group: "Full Body", tags: ["Bodyweight"], tracks: "bodyweight", sets: 3, reps: "8", notes: "Walk hands out to a plank and back.", loads: ["wrists"] },

  /* ---------------- Cardio & Conditioning ---------------- */
  { name: "Recumbent Bike", group: "Cardio & Conditioning", tags: ["Cardio"], tracks: "time", sets: 1, reps: "10–20 min", notes: "Very knee-friendly, back supported." },
  { name: "Upright Bike", group: "Cardio & Conditioning", tags: ["Cardio"], tracks: "time", sets: 1, reps: "10–20 min", notes: "Low knee impact." },
  { name: "Bike Erg", group: "Cardio & Conditioning", tags: ["Cardio", "CrossFit"], tracks: "time", sets: 1, reps: "10 min", notes: "Air bike-erg for intervals or steady work." },
  { name: "Assault Bike", group: "Cardio & Conditioning", tags: ["Cardio", "CrossFit"], tracks: "time", sets: 1, reps: "10 min", notes: "Scalable intensity, low knee impact." },
  { name: "Echo Bike Intervals", group: "Cardio & Conditioning", tags: ["Cardio", "CrossFit"], tracks: "time", sets: 8, reps: "20 sec hard / 40 sec easy", notes: "All-out sprints with recovery." },
  { name: "Rowing Machine", group: "Cardio & Conditioning", tags: ["Cardio", "CrossFit"], tracks: "time", sets: 1, reps: "10–15 min", notes: "Low-impact full body; drive with the legs." },
  { name: "Row (1000 m)", group: "Cardio & Conditioning", tags: ["Hyrox", "Cardio", "CrossFit"], tracks: "time", sets: 1, reps: "1000 m", notes: "A Hyrox station." },
  { name: "SkiErg", group: "Cardio & Conditioning", tags: ["Hyrox", "Cardio", "CrossFit"], tracks: "time", sets: 1, reps: "1000 m", notes: "Double-pole pull. A Hyrox station.", loads: ["shoulders"] },
  { name: "Running (1 km)", group: "Cardio & Conditioning", tags: ["Hyrox", "Cardio"], tracks: "time", sets: 1, reps: "1 km", notes: "The run between Hyrox stations.", loads: ["knees", "ankles"] },
  { name: "Treadmill Run", group: "Cardio & Conditioning", tags: ["Cardio"], tracks: "time", sets: 1, reps: "20–30 min", notes: "Steady running.", loads: ["knees", "ankles"] },
  { name: "Treadmill Walk (incline)", group: "Cardio & Conditioning", tags: ["Cardio"], tracks: "time", sets: 1, reps: "15–20 min", notes: "Steady pace; add incline instead of speed." },
  { name: "Interval Sprints", group: "Cardio & Conditioning", tags: ["Cardio", "Plyo"], tracks: "time", sets: 8, reps: "20 sec", notes: "Max-effort sprints with full recovery.", loads: ["knees", "ankles"] },
  { name: "Hill Sprints", group: "Cardio & Conditioning", tags: ["Cardio"], tracks: "time", sets: 6, reps: "15 sec", notes: "Short, steep, all-out.", loads: ["knees", "ankles"] },
  { name: "Shuttle Runs", group: "Cardio & Conditioning", tags: ["Cardio"], tracks: "time", sets: 5, reps: "4 × 20 m", notes: "Touch the line and turn.", loads: ["knees", "ankles"] },
  { name: "Elliptical", group: "Cardio & Conditioning", tags: ["Cardio"], tracks: "time", sets: 1, reps: "10–20 min", notes: "Low impact, smooth stride." },
  { name: "Stair Climber", group: "Cardio & Conditioning", tags: ["Cardio"], tracks: "time", sets: 1, reps: "10–15 min", notes: "Glutes plus cardio; repetitive knee load.", loads: ["knees"] },
  { name: "Swimming", group: "Cardio & Conditioning", tags: ["Cardio"], tracks: "time", sets: 1, reps: "20 min", notes: "Joint-friendly full-body cardio." },
  { name: "Cycling (outdoor)", group: "Cardio & Conditioning", tags: ["Cardio"], tracks: "time", sets: 1, reps: "30–60 min", notes: "Low-impact endurance." },
  { name: "Walking", group: "Cardio & Conditioning", tags: ["Cardio"], tracks: "time", sets: 1, reps: "20–40 min", notes: "The easiest cardio to recover from." },
  { name: "Hiking", group: "Cardio & Conditioning", tags: ["Cardio"], tracks: "time", sets: 1, reps: "30–60 min", notes: "Hills load the knees on the way down.", loads: ["knees"] },
  { name: "Rucking", group: "Cardio & Conditioning", tags: ["Cardio"], tracks: "time", sets: 1, reps: "30 min", notes: "Walking with a weighted pack.", loads: ["lower back"] },
  { name: "Jump Rope", group: "Cardio & Conditioning", tags: ["Cardio", "Plyo"], tracks: "time", sets: 1, reps: "5–10 min", notes: "Conditioning; high impact.", loads: ["knees", "ankles"] },
  { name: "Double-Unders", group: "Cardio & Conditioning", tags: ["CrossFit", "Plyo"], tracks: "bodyweight", sets: 3, reps: "30–50", notes: "Rope passes twice per jump.", loads: ["knees", "ankles"] },
  { name: "Battle Ropes", group: "Cardio & Conditioning", tags: ["CrossFit", "Cardio"], tracks: "time", sets: 4, reps: "30 sec", notes: "Fast alternating waves.", loads: ["shoulders"] },
  { name: "Jumping Jacks", group: "Cardio & Conditioning", tags: ["Bodyweight", "Cardio"], tracks: "time", sets: 3, reps: "45 sec", notes: "Classic warm-up conditioning.", loads: ["knees", "ankles"] },
  { name: "High Knees", group: "Cardio & Conditioning", tags: ["Bodyweight", "Cardio"], tracks: "time", sets: 3, reps: "30 sec", notes: "Drive the knees up fast.", loads: ["knees", "ankles"] },
  { name: "Butt Kicks", group: "Cardio & Conditioning", tags: ["Bodyweight", "Cardio"], tracks: "time", sets: 3, reps: "30 sec", notes: "Heels to glutes, quick feet.", loads: ["knees"] },

];
